@movieReferenceId = xxx

### GET list of movies
GET {{serviceUrl}}/api/v1/public/movies
Accept: application/json

### GET given movie
GET {{serviceUrl}}/api/v1/public/movies/{{movieReferenceId}}
Accept: application/json
